server:
  port: @server.port@
  ------------------------------------------------------------------------------------------------
spring:
  application:
    name: @project.name@
    description: @description@
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: @db.url@
    username: @db.user@
    password: @db.password@
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 3
  flyway:
    schemas: @db.schema@
  output:
    ansi:
      enabled: always
  ------------------------------------------------------------------------------------------------
kafka:
  bootstrap-servers: kenny-kafka1.bst1.rbkmoney.net:9092
  client-id: kafkaClient
  ssl:
    enabled: false
    trust-store-location: "test"
    trust-store-password: "test"
    key-store-location: "test"
    key-store-password: "test"
    key-password: "test"
    key-store-type: PKCS12
    trust-store-type: PKCS12
  consumer:
    concurrency: 8
    group-id: "KafkaListener"
    enable-auto-commit: false
    auto-offset-reset: earliest
    max-poll-records: 20
  topics:
    invoice:
      id: mg-invoice-100-2
      enabled: false
    payment:
      id: mg-payment-100-2
      enabled: false
    payout:
      id: mg-payout-100-2
      enabled: false
  ------------------------------------------------------------------------------------------------
storage:
  endpoint: storage:32827
  bucketName: files
  signingRegion: RU
  clientProtocol: HTTP
  clientMaxErrorRetry: 10
  socketTimeout: 50000
  connectionTimeout: 10000
  ------------------------------------------------------------------------------------------------
filestorage:
  url: http://file-storage:8022/file_storage
  clientTimeout: 5000
  urlLifeTimeDuration: 360
  timeZone: Europe/Moscow
  ------------------------------------------------------------------------------------------------
