spring:
  application:
    name: @project.name@
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: @db.url@
    username: @db.user@
    password: @db.password@
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 3
  flyway:
    schemas: @db.schema@
  output:
    ansi:
      enabled: always

storage:
  endpoint: localhost:32827
  bucketName: files
  signingRegion: RU
  clientProtocol: HTTP
  clientMaxErrorRetry: 10
  socketTimeout: 50000
  connectionTimeout: 10000

filestorage:
  url: http://file-storage:8022/file_storage
  clientTimeout: 5000
  urlLifeTimeDuration: 360
  timeZone: Europe/Moscow

kafka:
  bootstrap:
    servers: localhost:9092
  concurrency: 1
  processing:
    payout:
      topic: mg-payout-100-2
      enabled: false
    payment:
      topic: mg-invoice-100-2
      enabled: false
  ssl:
    enabled: false
    keystore-location: src/main/resources/cert/kenny-k.struzhkin.p12
    keystore-password: kenny
    key-password: kenny
    server-password: kenny12
    server-keystore-location: src/main/resources/cert/truststore.p12
